spring.application.name=transactionDemo
server.port=8090
# spring.datasource.url=jdbc:postgresql://aurora-pg-instance.c1musiwekb98.ap-south-1.rds.amazonaws.com:5432/microservice
# spring.datasource.username=test_master
# spring.datasource.password=admin123
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
